name: My test
on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout my branch
        uses: actions/checkout@v3
      - run: |
          echo "Bonjour"
          ls -al
          pwd