name: My test
on: [push]
jobs:
  ubuntu-wf:
    runs-on: ubuntu-latest
    steps:
      - name: checkout my branch
        uses: actions/checkout@v3
      - run: |
          echo "${{ github.event.commits[0].author.email }}"
          ls -al ${{ secrets.DIRNAME }}
          pwd